
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 29 21:30:51 CST 2020
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LKEY = 4;
  public static final int CHAR = 7;
  public static final int WORD = 33;
  public static final int LBRA = 6;
  public static final int CASE = 18;
  public static final int INT = 38;
  public static final int ENDMAIN = 41;
  public static final int FOR = 16;
  public static final int NOT = 49;
  public static final int SEMICOLON = 27;
  public static final int RPAR = 10;
  public static final int MULTOP = 22;
  public static final int QUOTATION = 31;
  public static final int OR = 14;
  public static final int BOOL = 29;
  public static final int COMMA = 25;
  public static final int NUM = 3;
  public static final int DIGIT = 2;
  public static final int ASSIGN = 42;
  public static final int MAIN = 19;
  public static final int IF = 12;
  public static final int ID = 53;
  public static final int DOT = 24;
  public static final int RELOP = 21;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int TRUE = 47;
  public static final int RKEY = 5;
  public static final int error = 1;
  public static final int PIPE = 34;
  public static final int RBRA = 8;
  public static final int MOD = 39;
  public static final int BREAK = 35;
  public static final int EQ = 51;
  public static final int SUMOP = 20;
  public static final int SWITCH = 11;
  public static final int VARTYPE = 28;
  public static final int NONE = 43;
  public static final int COLON = 26;
  public static final int ENDIF = 13;
  public static final int ELSE = 40;
  public static final int LETTER = 30;
  public static final int FUNC = 17;
  public static final int WHILE = 15;
  public static final int DEFAULT = 36;
  public static final int LOGOP = 23;
  public static final int END = 32;
  public static final int LPAR = 9;
  public static final int ASSIGNFOR = 44;
  public static final int FALSE = 48;
  public static final int RUN = 52;
  public static final int VAR = 37;
  public static final int PRINT = 50;
  public static final int STEP = 46;
}

